### ISSUE TITLE
Agency Identification V2

### ISSUE THREAD

**Issue by mbodeantor** [Police-Data-Accessibility-Project/data-source-identification#16]
#### Fixes

* Improving match rate of new URLs to those in the Agency table

#### Description

* Try to find a reliable source of geographic data from header, footer or other tags.
* Use it to narrow down agencies to match against

**Comment by josh-chamberlain** [comment]
Suggestion: also check urls of data sources for that agency. Some agencies have data about them on multiple municipal websites. We might have to be more careful—we're going to get similar URL patterns for different agencies using the same data portal and stuff. So, might not be worth it.

**Comment by maxachis** [comment]
So to make sure I understand, we'd be adding this information to the same JSON file the HTML Tag Collector is appending to, right? 

I figure the best bet is to go to the home page of the website and grab information there. My reasoning is:

1. The home page will most likely contain geographic information fairly well-described in a number of different tags. Take for example the [Baltimore County home page](https://www.baltimorecountymd.gov/), which contains "Baltimore" 43 times in the HTML, most prominently in the title. 
2. It's highly unlikely that a sub-page will refer to a different geographic location than the home page of the website, so getting data more reliably from the home page should work just as well as getting it from a subordinate page. 

We could then use that data in two possible ways:
1. Create a simple lookup table associating the root url with the locational data described in the title (or just the title itself). When we want to get the additional contextual information, we identify the root url and get the additional context. This would mean fewer requests overall, but does require implementing a new component for the lookup.
2. The repo already has a module which extracts the title and other information from the url in question (the HTML Tag Extractor). That could be extended/modified to also extract information from the home page at the same time. Less stuff to manage, but does load the HTML Tag Extractor with more work and means more scraping requests.

**Comment by maxachis** [comment]
Currently working on this in linked branch.

**Comment by maxachis** [comment]
I've created the relevant code and linked it in the above pull request. This code, as designed, will follow the implementation I mentioned above. It makes no other modifications. 

Before converting this PR to a draft, I'll need to figure out how to run the entire workflow and compare the results I get with the current suite of results, seeing if there are any distinctions. Because I'm not fully familiar with the workflow as yet, it's possible other components will need to be changed to ensure my changes are accounted for in URL identification.

**Comment by maxachis** [comment]
If I want to be able to see if I can make changes that improve the error rate, I first need a representative sample of data that is regularly applied to it, where I can get a sense of how often it's succeeding and failing, and then see how I can tweak that.

@mbodeantor @josh-chamberlain , is such a representative sample readily available, or would I need to find a way to create it?

**Comment by josh-chamberlain** [comment]
@maxachis in the past we used [common crawl](https://commoncrawl.org/latest-crawl) to get a list of URLs. One approach would be to limit the URLs to those containing "police", though it's your choice. Since we'll need to fetch URLs for both annotation and identification, please consider saving a script in a `common_crawl` directory in this repo! Let me know if that doesn't work.

Another option: using the [sitemap scraper](https://github.com/Police-Data-Accessibility-Project/scrapers/tree/main/utils/sitemap_scraper) on our existing agencies database.

**Comment by josh-chamberlain** [comment]
@maxachis no, I think someone just curl'd their API. We don't need automation or anything complicated at this moment.

**Comment by maxachis** [comment]
@josh-chamberlain I've created a PR to add a component to add additional information which should in theory assist in improving match rates, but I would likely need @EvilDrPurple or others to verify if it actually suits its intended purposes. We may need to try several different forms of training that include or don't include particular information.

I additionally don't know if this PR should necessarily be _closed_ because of this PR -- rather, it can be an additional possible way to improve the match rate.
