### ISSUE TITLE
common crawler enhancements

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-source-identification#66]
### Context

Follows #52 

Just tying up a couple loose ends we merged before addressing:

### Requirements

- I would also suggest we name/id batches this way: `YYMMDD-1` and count up from 1. The `name` is the same as the `id`. We could also add a code for the source, like `YYMMDD-CC-1` to show it's a common crawl batch, as opposed to future methods of generating batches.
- We should probably also use this moment to create a log of the batch somewhere—probably a machine readable file in the GitHub repo. we should track `id` `count` and `keywords` or other common crawl input data. We can add things over time, but those are to get it started.
- Let's avoid making this run daily. Until we process the first batch, we're not ready for the second. These will pile up + get intimidating, so we can click the action manually for now.

#### batch file example

name | count | keywords
-- | -- | --
240403-CC-1 | 10000 | police,.gov
240403-CC-2 | 10000 | police,.gov

**Comment by maxachis** [comment]
@josh-chamberlain 

## Logging batches
I think storing logs is a good idea, and my bias would be to store them in the PostgreSQL database, for a few reasons

1.  An in-repo log batch will need to be committed every time the Github Action is run, which could produce commit clutter, particularly if we use the action aggressively or use it to store information about other generated batches
2. Reduces clutter in the repo itself -- minor, but worth noting
3. If we want to use information from the batch logs in other applications, it'll be easier to access it in SQL than in the repository. 
4. It'll be considerably easier for us to add (or remove) columns or otherwise modify the format of batch information
5. We can be more verbose in identifying each batch -- for example, having a column labeled `Source` that explicitly states `CommonCrawl` instead of the more ambiguous `CC`. We can also be more precise in identifying the datetime where a batch occurs, which could be useful for debugging.
6. If we ever want to identify _where_ we got particular URLs from, it'll be easier to do that in the database

My biases are premised on the assumption that we'll be gathering a significant number of batches, from multiple sources, over time, and that it will be relevant for other work. If that's not true, a SQL table might not be necessary. And regardless of which format we choose, we could convert it into the other at a later date if we decide to change.

## Batching by URL count

There are a few considerations worth taking into account when considering batching by URL count

1. The way Common Crawl (and by extension my code) works is that it pulls results on a per-page basis. Each page is about 15,000 records/urls, and depending on the search parameters (i.e., the `*url` parameter, for example), the number of pages can be in the thousands. 
8. There's not an easy way of knowing how many relevant records are in each page (with relevancy in this case being based on a keyword match -- we probably don't want `.gov` websites that don't reference police). A single page can yield several hundred relevant urls, or none at all.
9. Pulling a single page of common crawl takes a not-insubstantial amount of time. Typically only a few seconds, but those few seconds stack up. 

This makes it somewhat more complicated when trying to pull a specific number of urls -- I could adjust the code to keep pulling pages until exceeding a certain threshold, but it'll be hard to predict how long that might take.

**Comment by josh-chamberlain** [comment]
@maxachis 

Logs: OK, all your points make sense. Let's have a column labeled `source`, and have more precise datetimes. 

That said, we'll have a significant amount of batches someday, but right now we're not even crawling. I do think that for today/this month, a table in the repo is sufficient. By next week, maybe it'll have 3 rows in it? We can apply what we learn there → establish formal logging from there. If that sounds miserable to you, I'm open to just using Postgres right away. I think adding a simple API middle layer would be beneficial, rather than writing direct to db. @mbodeantor I would be curious to hear your thoughts on this.

URL count 1–3: OK, let's _not_ batch by URL count. Let's try getting one page at a time—it's OK if the batches are small.

**Comment by maxachis** [comment]
@josh-chamberlain Working on this, but programmatically getting the most up-to-date Common Crawl index is not a straightforward process -- the best options I've found involve utilizing Amason S3 to access the Common Crawl CLI or scraping a web page. My opinion is that this might be a nice-to-have until we are further along in the common crawl process.

**Comment by maxachis** [comment]
@mbodeantor Sounds good. My current PR will commit a csv to file, so we should have that covered.
